// `DIGTYP.H` основные определения.
// редакции от [13.12.2012], [26.01.2018]

#ifndef  DIG_TYPES_H
#define  DIG_TYPES_H

typedef  signed char       i8;
typedef  signed short      i16;
typedef  signed long       i32;
typedef  signed long long  i64;

typedef  unsigned char       u8;
typedef  unsigned short      u16;
typedef  unsigned long       u32;
typedef  unsigned long long  u64;

/// #ifdef  _WIN32
///    #pragma pack( push, 1 ) // ПРАВИЛЬНАЯ упаковка структур
/// #endif

#endif /* DIG_TYPES_H */
